### ISSUE TITLE
Failed to build Sushid

### ISSUE THREAD

**Issue by bajro17** [SushiCoinHQ/SushiCoin#103]
This is what I get when try to build it 
Error target sushid failed to compile:
cc: error: Folder: No such file or directory
cc: error: 4/SushiCoin/lib/scrypt/src/../ext: No such file or directory
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/bajro/Desktop/Untitled Folder 4/SushiCoin/bin/sushid'  -rdynamic  -lsqlite3 -L/home/bajro/Desktop/Untitled Folder 4/SushiCoin/lib/scrypt/src/../ext -lscrypt -lz `command -v pkg-config > /dev/null && pkg-config --libs libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs libcrypto || printf %s '-lcrypto'` -lgmp -lyaml -lpcre -lm -lgc -lpthread /usr/lib/crystal/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`

**Comment by tbrand** [comment]
Could you show me your build command?

This should be fine to work.
```bash
> shards build
```

**Comment by bajro17** [comment]
![screenshot from 2018-03-18 05-15-37](https://user-images.githubusercontent.com/16452914/37562541-7a431a08-2a6b-11e8-99e6-c8da0e3d0f60.png)

**Comment by tbrand** [comment]
It seems that it failed to compile https://github.com/ysbaddaden/scrypt-crystal .
So let me check the error message's correctness.

Does that folder `SushiChain/lib/scrypt/src/../ext` exist?

**Comment by tbrand** [comment]
Hmm, so that's pretty strange...
Could move the folder to somewhere else in order to remove the spaces in the path?
`Untitled Folder 4` includes spaces, it's suspicious.

**Comment by bajro17** [comment]
yes I fix it I just change folder name to sushi without spaces and it compile normal

**Comment by tbrand** [comment]
You mean you've built sushid successfully?

**Comment by bajro17** [comment]
yes whole code is build successfully. Maybe will be good to mention this on build section in case someone else have same problem or to try fix this. Thank you so much for help

**Comment by tbrand** [comment]
Awesome :+1:
OK, I'll add it. Thanks for the feedback.

**Comment by bajro17** [comment]
I will try help how much I can it look awesome code verry good job. I will try little test and give you feedback if find some more problems

**Comment by tbrand** [comment]
That's awesome! You can open issues for each feedback which you've found! :+1:
