### ISSUE TITLE
Node json issue

### ISSUE THREAD

**Issue by bajro17** [SushiCoinHQ/SushiCoin#104]
I was following steps described in QuickStart and come to step 
**Running a local private node on the testnet**
but it refuse to connect on aws 
this is error
Missing json attribute: fee at 1:17361
(I delete address here because of security)amazonaws.com:3000

**Comment by tbrand** [comment]
Your command is correct but the version of public testnet at sushichain.io is too old.
We will update them. Sorry for the inconvenient.

**Comment by kingsleyh** [comment]
Hi - I've deployed the latest now - but having a problem with the Loadbalancer - so until it's gets fixed - you can use http://sushicoin.io:3000 as the connecting node (which goes direct to the EC instance instead of via LB)

**Comment by kingsleyh** [comment]
This is now resolved - the latest version is deployed and the testnet is fully operational on either

* http://testnet.sushichain.io:3000
* https://testnet.sushichain.io:3443
