### ISSUE TITLE
Sync versions of sushid node

### ISSUE THREAD

**Issue by kingsleyh** [SushiCoinHQ/SushiCoin#106]
put the deployed version on a status endpoint and when any node connects to the node - it should verify it has the same version - if the versions are different - report a message advising the difference and what to do - e.g. upgrade or whatever

currently deployed version from TeamCity makes a binary called sushid_<build_number> each time the build runs and it deploys it when running deploy from TeamCity. it would be cool if when building the binary it could take in a version number  - then TeamCity could pass the build number when it builds the binary.

**Comment by tbrand** [comment]
will do it. thanks

**Comment by tbrand** [comment]
> will the downstream nodes try to reconnect to the main testnet again?

Nop

> or will they never find out the code has changed unless someone stops and restarts one of the downstream nodes?

Yeah, sadly that' correct.
I have an idea for saving a nodes table and loading it during restarting.

But the node cannot avoid to occur a bit downtime.
If the nodes have redundancy like as our testnet system using LB, enable to avoid it.
