### ISSUE TITLE
Prevent DDoS attacks

### ISSUE THREAD

**Issue by tbrand** [SushiCoinHQ/SushiCoin#26]
We can create a blacklist for it.

**Comment by kingsleyh** [comment]
if we host the mainnet and testnet on AWS we can put cloudflare or cloudfront in front to prevent DDoS as well

**Comment by watzon** [comment]
How are you thinking the blacklist would work @tbrand? Maybe connections that seem like they're DDOSing could be automatically added?

**Comment by kingsleyh** [comment]
I think a node should always be running behind a load balancer and firewall - so blacklisting would need to happen at the firewall - this is not an effective way though - better to use cloudflare ddos - if the node is public and it’s just running behind a home router - Maybe blacklisting could work - but it might kill the home router anyway - so prob better to blacklist on the router
