### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by tbrand** [SushiCoinHQ/SushiCoin#27]
For who don't have a crystal environment.

**Comment by kingsleyh** [comment]
I think we should create a docker that we can load onto some AWS EC2 instances to instantly spin up testnets and mainnets

**Comment by kingsleyh** [comment]
The standard practise with Docker is to create a docker instance per process and manage them with docker-compose - so we could have 3 instances:
1. sushid
2. sushim
3. sushi
managed by docker compose

**Comment by kingsleyh** [comment]
see this new project I created:  https://github.com/SushiCoinHQ/SushiDocker

**Comment by kingsleyh** [comment]
All done and tested and added a link from wiki
