### ISSUE TITLE
Add a config diretory and config file

### ISSUE THREAD

**Issue by watzon** [SushiCoinHQ/SushiCoin#39]
Most coins don't require you to enter connection information every time you run the daemon. Instead all of that info is stored in a `~/.coinname/coinname.config` file. I propose that we come up with a configuration file structure that will allow us to list node connection information, privacy settings for our node, default wallet location, etc.

**Comment by kingsleyh** [comment]
we create a config file for the node (sushid) - we can keep the current cli options as overrides. but if not specified then it takes them from the config file? - a default config file would go in something like ~/.sushid.conf - and have a cli option to override the conf file location

**Comment by watzon** [comment]
Ideally I think we should follow suit with other coins and have a `~/.shushicoin` directory with `sushicoin.conf` inside of it. The config file should definitely be overridable though. This way we have a single directory to store the config file, default wallet, and the database, as well as any other potential files we may need.

I also think the default configuration file, database, and default wallet should be created the first time `sushid` is launched.

**Comment by kingsleyh** [comment]
directory structure could be `~/.sushicoin/config/{node.yml, cli.yml}`

also we should create config for sushi client (most widely used by users) as well as config for the node (sushid) - I think there is not much reason to start a local node unless running a public one

**Comment by watzon** [comment]
Here's what I imagine the directory structure being eventually.

![image](https://user-images.githubusercontent.com/4535422/35665082-cb675dac-06e1-11e8-9307-ff48d3539d08.png)

**Comment by tbrand** [comment]
Done.
