### ISSUE TITLE
build in SSL support to sushid and for the miners

### ISSUE THREAD

**Issue by kingsleyh** [SushiCoinHQ/SushiCoin#62]
In order to run the testnet as https - the miners must make an SSL connection to the testnet - and also sushid must be able to start in SSL mode with the certs (like Kemal does)

**Comment by kingsleyh** [comment]
Do we want to encourage general uses to run public nodes? If more users run nodes it will increase the size of the network which is a good thing. In some blockchains they don't allow you to run a public node connected to the mainnet unless you have a certain number of coins in your wallet.

**Comment by tbrand** [comment]
Yup, everyone can run node at first. The restriction feature can be added after the publishing.

Additionally, I think SSL feature should be supported in LB or instance level, not the binary.
Because it also restrict users to run the node or mining.
So we don't have to do this, what you think?

**Comment by kingsleyh** [comment]
I wanted to provide an option to use SSL for those that want to - but not make it mandatory. But maybe this can be done later on.  At the moment the testnet.sushichain.io has a redirect from http to https - but if I remove that then we can just operate on HTTP at the start.

**Comment by tbrand** [comment]
make sense

**Comment by kingsleyh** [comment]
The LB is now configured to forward http port 3000 to 3000 on the server instance. And https 3443 is forwarded to 3000 on the server instance. 

sushid, sushim, sushi work fine against http 3000 

sushid does not sync the remote blockchain when using https on port 3443
sushim fails the handshake with 400 against https on port 3443
sushi works fine

I don't know if these problems with SSL need fixing in our code or if it's a AWS config?

**Comment by kingsleyh** [comment]
This is fixed in pull request #94
