### ISSUE TITLE
Maybe prevent sending coins when a wallet has not enough coins?

### ISSUE THREAD

**Issue by kingsleyh** [SushiCoinHQ/SushiCoin#86]
```bash
>./sushi wallet amount -w wallet1.json -n http://localhost:3000
```

    show Sushi coins amount of 
    VDAwYTUwYjllNmNiNGE3YjMxYjE3ZmVjZTk1Njg4MzM0ODM5MDA4ZTY4ZjdlZTNh
    0

```bash
./sushi tx send -n http://localhost:3000 -w wallet1.json -a VDAxYmIwNWIyOTFlNGY3ZDViOTliY2UyNTE0MTI5MmVjMTI3NGI5OTZhNzhkZmY1 -m 1
```
    
    successfully create your transaction!
    => 6fda20462a3587c062099bfd83aec9b8039091840a7526aa780a52bc385d8e3c

I guess this transaction would hopefully be rejected eventually (after mining) because of having no coins in the wallet - but it would be nice to reject the send right away if there are not enough coins at that point in time (if we are able to know this information)

**Comment by tbrand** [comment]
> I guess this transaction would hopefully be rejected eventually (after mining) because of having no coins in the wallet

Correct!
1. https://github.com/SushiCoinHQ/SushiCoin/blob/master/src/core/blockchain.cr#L132
2. https://github.com/SushiCoinHQ/SushiCoin/blob/master/src/core/blockchain/transaction.cr#L77

> but it would be nice to reject the send right away if there are not enough coins at that point in time

The code is here
https://github.com/SushiCoinHQ/SushiCoin/blob/master/src/core/blockchain.cr#L122

But it's suspicious that if there are unconfirmed amount of coins that you will get, the user should be able to create the transaction. So if we will do this, I think we should check the **unconfirmed** amount.
