### ISSUE TITLE
do not calculate_fee from the transactions but record it into transactions

### ISSUE THREAD

**Issue by tbrand** [SushiCoinHQ/SushiCoin#93]
currently, calculating fees are done during the runtime. but it should be cached into transactions for a performance optimization.

**Comment by tbrand** [comment]
May be we can fix a fee for each block.

**Comment by kingsleyh** [comment]
what is the current performance without this optimisation? 

I think we might want to change the fees as required. 
Also we might need to have smaller units of coin.

Imagine if we are listed on an exchange and 1 sushicoin == $1000 - if the block fee is 1 sushicoin thats pretty expensive. So we might want to track the exchange rates and keep the fee at say $1 = which would be 0.001 of a sushicoin.

Also if I want to send you $500 worth of coin - then I would need to be able to specify: 0.5

The different denominations have names in Ethereum:
https://steemit.com/cryptocurrency/@encryptcy/ethereum-denominations
